name = "logic"
uuid = "71af330d-9551-40af-bd9f-dd36b4d12b46"
version = "0.0.7"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["BenchmarkTools"]
